version: "3"
services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "4000:${PORT}"
    environment:
      DBUSER: ${DBUSER}
      DBPASS: ${DBPASS}
      DBNAME: ${DBNAME}
      DBHOST: db
      PORT: ${PORT}
      JWT_SECRET: ${JWT_SECRET}
      ADM_PASS: ${ADM_PASS}
      ADM_LOGIN: ${ADM_LOGIN}

  db:
    image: postgres:13.4-alpine
    environment:
      POSTGRES_USER: ${DBUSER}
      POSTGRES_PASSWORD: ${DBPASS}
